{
    "name": "Financial Report configuration",
    "version": "18.0.0.0.0",
    "depends": ["web"],
    "author": "Smile",
    "license": "AGPL-3",
    "description": "",
    "summary": "",
    "website": "",
    "category": "Tools",
    "sequence": 20,
    "installable": True,
    "application": False,
    "images": ["static/description/banner.gif"],
}
